import { Noto_Sans_JP } from '@next/font/google';
import type { Metadata } from 'next';
import Provider from "./Provider";

const notoSansJP700 = Noto_Sans_JP({
  weight: '700',
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoSansJP700.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
