version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    volumes:
      - ../:/workspace
    command: bash
    tty: true
    depends_on:
      - db
      - localstack
  db:
    image: postgres:latest
    container_name: db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "33333:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack/
    ports:
      - 4566:4566
volumes:
  postgres_data:
  localstack_data:
